package com.lhf.game.shared.enums;

public enum EquipmentTypes
{
    LIGHTARMOR, MEDIUMARMOR, HEAVYARMOR, SIMPLEMELEEWEAPONS, MARTIALWEAPONS, SIMPLERANGEDWEAPONS, RANGEDWEAPONS, PADDED, LEATHER, STUDDEDLEATHER, HIDE, CHAINSHIRT, SCALEMAIL, BREASTPLATE, HALFPLATE, RINGMAIL, CHAINMAIL, SPLINTMAIL, PLATEMAIL, SHIELD, CLUB, DAGGER, GREATCLUB, HANDAXE, JAVELIN, LIGHTHAMMER, MACE, QUARTERSTAFF, SICKLE, SPEAR, LIGHTCROSSBOW, DART, SHORTBOW, SLING, BATTLEAXE, FLAIL, GLAIVE, GREATAXE, GREATSWORD, HALBERD, LANCE, LONGSWORD, MAUL, MORNINGSTAR, PIKE, RAPIER, SCIMITAR, SHORTSWORD, TRIDENT, WARPICK, WARHAMMER, WHIP, BLOWGUN, HEAVYCROSSBOW, HANDCROSSBOW, LONGBOW, NET, WARLOCK, MONSTERPART
}
